### ISSUE TITLE
Crashing on mouse selection

### ISSUE THREAD

**Issue by imincik** [DaveDavenport/rofi#313]
rofi is crashing when selecting item by mouse.

How to reproduce:
* $  rofi -show run
* choose item by mouse
* Segmentation fault (core dumped)

Version:
* rofi: 0.15.12
* OS: Ubuntu Trusty, i3wm

**Comment by DaveDavenport** [comment]
I cannot reproduce this? can you pastebin the output of 
```
rofi -dump-xresources
```

And if possible get a backtrace from the core dump? 

Thanks.

**Comment by imincik** [comment]
$ rofi -dump-xresources
```
! Enabled modi
rofi.modi:                           window,run,ssh
! Window opacity
rofi.opacity:                        100
! Window width
rofi.width:                          50
! Number of lines
rofi.lines:                          15
! Number of columns
rofi.columns:                        1
! Font to use
rofi.font:                           Ubuntu 10
! Foreground color
rofi.fg:                             #888888
! Background color
rofi.bg:                             #222222
! Foreground color for active row
rofi.fg-active:                      #268BD2
! Foreground color for urgent row
rofi.fg-urgent:                      #DC322F
! Foreground color for highlighted active row
rofi.hlfg-active:                    #FDF6E3
! Foreground color for highlighted urgent row
rofi.hlfg-urgent:                    #FDF6E3
! Background color for active row
rofi.bg-active:                      #FDF6E3
! Background color for urgent row
rofi.bg-urgent:                      #FDF6E3
! Background color for highlighted active row
rofi.hlbg-active:                    #268BD2
! Background color for highlighted urgent row
rofi.hlbg-urgent:                    #DC322F
! Background color for alternating row
rofi.bgalt:                          #222222
! Foreground color for highlighted row
rofi.hlfg:                           #ffffff
! Background color for highlighted row
rofi.hlbg:                           #285577
! Border color
rofi.bc:                             #000000                                                                                                                                                      
! Use extended color scheme                                                                                                                                                                       
rofi.color-enabled:                  false                                                                                                                                                        
! Color scheme for normal row                                                                                                                                                                     
rofi.color-normal:                   #fdf6e3,#002b36,#eee8d5,#586e75,#eee8d5
! Color scheme for urgent row
rofi.color-urgent:                   #fdf6e3,#dc322f,#eee8d5,#dc322f,#fdf6e3
! Color scheme for active row
rofi.color-active:                   #fdf6e3,#268bd2,#eee8d5,#268bd2,#fdf6e3
! Color scheme window
rofi.color-window:                   #fdf6e3,#002b36
! Border width
rofi.bw:                             1
! Location on screen
rofi.location:                       0
! Padding
rofi.padding:                        5
! Y-offset relative to location
rofi.yoffset:                        0
! X-offset relative to location
rofi.xoffset:                        0
! Always show number of lines
rofi.fixed-num-lines:                false
! Terminal to use
rofi.terminal:                       rofi-sensible-terminal
! Ssh client to use
rofi.ssh-client:                     ssh
! Ssh command to execute
rofi.ssh-command:                    {terminal} -e {ssh-client} {host}
! Run command to execute
rofi.run-command:                    {cmd}
! Command to get extra run targets
rofi.run-list-command:               
! Run command to execute that runs in shell
rofi.run-shell-command:              {terminal} -e {cmd}
! Disable history in run/ssh
rofi.disable-history:                false
! Use levenshtein sorting
rofi.levenshtein-sort:               false
! Set case-sensitivity
rofi.case-sensitive:                 false
! Enable sidebar-mode
rofi.sidebar-mode:                   false
! Set lazy filter limit
rofi.lazy-filter-limit:              15000
! Row height (in chars)
rofi.eh:                             1
! Enable auto select mode
rofi.auto-select:                    false
! Parse hosts file for ssh mode
rofi.parse-hosts:                    false
! Parse known_hosts file for ssh mode
rofi.parse-known-hosts:              true
! Set the modi to combine in combi mode
rofi.combi-modi:                     window,run
! Do a more fuzzy matching
rofi.fuzzy:                          false
! Use glob matching
rofi.glob:                           false
! Use regex matching
rofi.regex:                          false
! Tokenize input string
rofi.tokenize:                       true
! Monitor id to show on
rofi.m:                              -1
! Margin between rows
rofi.line-margin:                    2
! Pre-set filter
rofi.filter:                         
! Separator style (none, dash, solid)
rofi.separator-style:                solid
! Hide scroll-bar
rofi.hide-scrollbar:                 true
! Show markup
rofi.markup-rows:                    false
! Fullscreen
rofi.fullscreen:                     false
! Fake transparency
rofi.fake-transparency:              false
! DPI
rofi.dpi:                            -1
! Threads to use for string matching
rofi.threads:                        1
! Scrollbar width
rofi.scrollbar-width:                8
! Pidfile location
rofi.pid:                            /run/user/1000/rofi.pid
! Keybinding
rofi.kb-primary-paste:               Control+Shift+v,Shift+Insert
! Keybinding
rofi.kb-secondary-paste:             Control+v,Insert
! Keybinding
rofi.kb-clear-line:                  Control+u
! Keybinding
rofi.kb-move-front:                  Control+a
! Keybinding
rofi.kb-move-end:                    Control+e
! Keybinding
rofi.kb-move-word-back:              Alt+b
! Keybinding
rofi.kb-move-word-forward:           Alt+f
! Keybinding
rofi.kb-move-char-back:              Left,Control+b
! Keybinding
rofi.kb-move-char-forward:           Right,Control+f
! Keybinding
rofi.kb-remove-word-back:            Control+Alt+h
! Keybinding
rofi.kb-remove-word-forward:         Control+Alt+d
! Keybinding
rofi.kb-remove-char-forward:         Delete,Control+d
! Keybinding
rofi.kb-remove-char-back:            BackSpace,Control+h
! Keybinding
rofi.kb-accept-entry:                Control+j,Control+m,Return,KP_Enter
! Keybinding
rofi.kb-accept-custom:               Control+Return
! Keybinding
rofi.kb-accept-entry-continue:       Shift+Return
! Keybinding
rofi.kb-mode-next:                   Shift+Right,Control+Tab
! Keybinding
rofi.kb-mode-previous:               Shift+Left,Control+Shift+Tab
! Keybinding
rofi.kb-toggle-case-sensitivity:     grave,dead_grave
! Keybinding
rofi.kb-delete-entry:                Shift+Delete
! Keybinding
rofi.kb-row-left:                    Control+Page_Up
! Keybinding
rofi.kb-row-right:                   Control+Page_Down
! Keybinding
rofi.kb-row-up:                      Up,Control+p,Shift+Tab
! Keybinding
rofi.kb-row-down:                    Down,Control+n
! Keybinding
rofi.kb-row-tab:                     Tab
! Keybinding
rofi.kb-page-prev:                   Page_Up
! Keybinding
rofi.kb-page-next:                   Page_Down
! Keybinding
rofi.kb-row-first:                   Home,KP_Home
! Keybinding
rofi.kb-row-last:                    End,KP_End
! Keybinding
rofi.kb-row-select:                  Control+space
! Keybinding
rofi.kb-cancel:                      Escape,Control+bracketleft
! Keybinding
rofi.kb-custom-1:                    Alt+1
! Keybinding
rofi.kb-custom-2:                    Alt+2
! Keybinding
rofi.kb-custom-3:                    Alt+3
! Keybinding
rofi.kb-custom-4:                    Alt+4
! Keybinding
rofi.kb-custom-5:                    Alt+5
! Keybinding
rofi.kb-custom-6:                    Alt+6
! Keybinding
rofi.kb-custom-7:                    Alt+7
! Keybinding
rofi.kb-custom-8:                    Alt+8
! Keybinding
rofi.kb-custom-9:                    Alt+9
! Keybinding
rofi.kb-custom-10:                   Alt+0
! Keybinding
rofi.kb-custom-11:                   Alt+Shift+1
! Keybinding
rofi.kb-custom-12:                   Alt+Shift+2
! Keybinding
rofi.kb-custom-13:                   Alt+Shift+3
! Keybinding
rofi.kb-custom-14:                   Alt+Shift+4
! Keybinding
rofi.kb-custom-15:                   Alt+Shift+5
! Keybinding
rofi.kb-custom-16:                   Alt+Shift+6
! Keybinding
rofi.kb-custom-18:                   Alt+Shift+8
! Keybinding
rofi.kb-custom-17:                   Alt+Shift+7
! Keybinding
rofi.kb-custom-19:                   Alt+Shift+9
! Keybinding
rofi.kb-screenshot:                  Alt+Shift+S
! Keybinding
rofi.kb-toggle-sort:                 Alt+grave
! Keybinding
rofi.key-window:                     
! Keybinding
rofi.key-run:                        
! Keybinding
rofi.key-ssh:                        
```

**Comment by imincik** [comment]
@DaveDavenport, do I need 'debug build' to provide usable backtrace ?

**Comment by DaveDavenport** [comment]
If  possible yes.. I will setup a VM later to see if I can reproduce this.

**Comment by imincik** [comment]
Output from non-debug build

$ gdb rofi core 
```
GNU gdb (Ubuntu 7.7.1-0ubuntu5~14.04.2) 7.7.1
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from rofi...(no debugging symbols found)...done.
[New LWP 16052]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `rofi -show run'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00000000004092c7 in ?? ()
(gdb) bt
#0  0x00000000004092c7 in ?? ()
#1  0x000000000040ada0 in ?? ()
#2  0x000000000040ae8d in ?? ()
#3  0x0000000000406cf0 in ?? ()
#4  0x00007f09e714dec5 in __libc_start_main (main=0x4060b0, argc=3, argv=0x7ffe3ee2d6b8, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7ffe3ee2d6a8)
    at libc-start.c:287
#5  0x0000000000406faa in ?? ()
```

**Comment by DaveDavenport** [comment]
Created a ubuntu 14.04  virtualmachine  installed i3-wm used the above config, but been unable to reproduce this.

Can you try getting a backtrace with debug symbols.?

**Comment by imincik** [comment]
@DaveDavenport , thank you very much for your time. I will try my best to compile with debug and get back with backtrace.

**Comment by DaveDavenport** [comment]
Please re-open when more information.
