### ISSUE TITLE
Segfault on latest versions (including from -git)

### ISSUE THREAD

**Issue by HalosGhost** [DaveDavenport/rofi#818]
## Version
Version: 1.5.1-34-git-a92bcc28-dirty (makepkg)

## Configuration
https://ptpb.pw/Coy2

## Launch Command
``rofi -show run``

## Steps to reproduce

* `rofi -show run`

## What behaviour you see

* it segfaults

## What behaviour you expect to see

* the run rofi menu shows up

## other notes
oddly, reverting to an older version did not help. To me, that suggests it might have something to do with a library rofi links to?

Additionally, here's the segfault coredump:

```
           PID: 29189 (rofi)
           UID: 1000 (halosghost)
           GID: 1000 (halosghost)
        Signal: 11 (SEGV)
     Timestamp: Sun 2018-06-17 14:36:00 CDT (2min 13s ago)
  Command Line: rofi -dmenu -p \=
    Executable: /usr/bin/rofi
 Control Group: /user.slice/user-1000.slice/session-c1.scope
          Unit: session-c1.scope
         Slice: user-1000.slice
       Session: c1
     Owner UID: 1000 (halosghost)
       Boot ID: 1299b57aaaad4f3393b844ba68864822
    Machine ID: 653ee8fe172946a2afce8fa5d9ac8d3a
      Hostname: Atlas
       Storage: /var/lib/systemd/coredump/core.rofi.1000.1299b57aaaad4f3393b844ba68864822.29189.1529264160000000.lz4
       Message: Process 29189 (rofi) of user 1000 dumped core.

                Stack trace of thread 29189:
                #0  0x00007fc7eb90f361 tt_face_get_colr_layer (libfreetype.so.6)
                #1  0x00007fc7eb8ca4f8 FT_Render_Glyph_Internal (libfreetype.so.6)
                #2  0x00007fc7ee0a11c5 n/a (libcairo.so.2)
                #3  0x00007fc7ee049adf n/a (libcairo.so.2)
                #4  0x00007fc7ee0955bf n/a (libcairo.so.2)
                #5  0x00007fc7ee093184 n/a (libcairo.so.2)
                #6  0x00007fc7ee0967a9 n/a (libcairo.so.2)
                #7  0x00007fc7ee005541 n/a (libcairo.so.2)
                #8  0x00007fc7ee08bf13 n/a (libcairo.so.2)
                #9  0x00007fc7ee059d97 n/a (libcairo.so.2)
                #10 0x00007fc7ee00f253 n/a (libcairo.so.2)
                #11 0x00007fc7ee066fe4 cairo_show_glyphs (libcairo.so.2)
                #12 0x00007fc7ee551e4c n/a (libpangocairo-1.0.so.0)
                #13 0x00007fc7ee55207c n/a (libpangocairo-1.0.so.0)
                #14 0x00007fc7ee32c2df pango_renderer_draw_glyph_item (libpango-1.0.so.0)
                #15 0x00007fc7ee32e3ea pango_renderer_draw_layout_line (libpango-1.0.so.0)
                #16 0x00007fc7ee32e7d9 pango_renderer_draw_layout (libpango-1.0.so.0)
                #17 0x00007fc7ee54ed0b n/a (libpangocairo-1.0.so.0)
                #18 0x00005637336ca3a4 textbox_draw (rofi)
                #19 0x00005637336c89e5 widget_draw (rofi)
                #20 0x00005637336c7aab box_draw (rofi)
                #21 0x00005637336c89e5 widget_draw (rofi)
                #22 0x00005637336c7aab box_draw (rofi)
                #23 0x00005637336c89e5 widget_draw (rofi)
                #24 0x00005637336c7aab box_draw (rofi)
                #25 0x00005637336c89e5 widget_draw (rofi)
                #26 0x00005637336bfea8 rofi_view_update (rofi)
                #27 0x00005637336c0b03 rofi_view_create (rofi)
                #28 0x00005637336d5045 dmenu_switcher_dialog (rofi)
                #29 0x00005637336bd77e startup (rofi)
                #30 0x00007fc7efe691d6 g_main_context_dispatch (libglib-2.0.so.0)
                #31 0x00007fc7efe695b1 n/a (libglib-2.0.so.0)
                #32 0x00007fc7efe698e2 g_main_loop_run (libglib-2.0.so.0)
                #33 0x00005637336b3766 main (rofi)
                #34 0x00007fc7ed6a706b __libc_start_main (libc.so.6)
                #35 0x00005637336b386a _start (rofi)

                Stack trace of thread 29194:
                #0  0x00007fc7ed771ea9 __poll (libc.so.6)
                #1  0x00007fc7efe69523 n/a (libglib-2.0.so.0)
                #2  0x00007fc7efe6963e g_main_context_iteration (libglib-2.0.so.0)
                #3  0x00007fc7efe69692 n/a (libglib-2.0.so.0)
                #4  0x00007fc7efe91a2a n/a (libglib-2.0.so.0)
                #5  0x00007fc7eda47075 start_thread (libpthread.so.0)
                #6  0x00007fc7ed77c53f __clone (libc.so.6)
```

**Comment by DaveDavenport** [comment]
Looks like it crashes on the font handling (pango/fontconfig).

What distro do you run?  and what pango and fontconfig version?

**Comment by HalosGhost** [comment]
I run Archlinux, so I'm mostly on the latest everything.

Fontconfig: 2.13.0+10+g58f5285-1
Pango: 1.42.1-1

**Comment by gBopHuk** [comment]
Confirm in ALTLinux 

fontconfig-2.12.6
libpango-1.40.14

**Comment by gBopHuk** [comment]
Gdb wtih debuginfo files

```
(gdb) run rofi
Starting program: /usr/bin/rofi rofi
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Missing separate debuginfo for /usr/lib64/libfreetype-infinality/libfreetype.so.6
Try to install the hash file /usr/lib/debug/.build-id/89/882892327b85a0c5cdd94b601cca6efa563622.debug

Program received signal SIGSEGV, Segmentation fault.
yylex (yylval_param=yylval_param@entry=0x7fffffffd838, yylloc_param=yylloc_param@entry=0x7fffffffd858) at lexer/theme-lexer.l:244
244	YY_LLOC_START
(gdb) bt
#0  yylex (yylval_param=yylval_param@entry=0x7fffffffd838, yylloc_param=yylloc_param@entry=0x7fffffffd858) at lexer/theme-lexer.l:244
#1  0x00000000004177b5 in yyparse (
    what=what@entry=0x4451c0 <resources_resource_data+216> "/**\n * rofi -dump-theme output.\n **/\n* {\n    selected-normal-foreground:  @lightbg;\n    foreground:", ' ' <repeats 18 times>, "rgba ( 0, 43, 54, 100 % );\n    normal-foreground:", ' ' <repeats 11 times>, "@foreground;\n    altern"...)
    at lexer/theme-parser.c:3443
#2  0x000000000041af66 in rofi_theme_parse_string (
    string=0x4451c0 <resources_resource_data+216> "/**\n * rofi -dump-theme output.\n **/\n* {\n    selected-normal-foreground:  @lightbg;\n    foreground:", ' ' <repeats 18 times>, "rgba ( 0, 43, 54, 100 % );\n    normal-foreground:", ' ' <repeats 11 times>, "@foreground;\n    altern"...) at lexer/theme-lexer.l:663
#3  0x00000000004119c5 in main (argc=<optimized out>, argv=0x7fffffffe408) at source/rofi.c:898
(gdb) 

```

**Comment by DaveDavenport** [comment]
@gBopHuk  That seems to be a completely different crash then the previous one. (first one crashes in rendering, yours in theme parsing.).
Can you create a separate issue? Thanks.

**Comment by gBopHuk** [comment]
Sorry!
I'va created new issue https://github.com/DaveDavenport/rofi/issues/825

**Comment by DaveDavenport** [comment]
No problem, as a user hard to tell. Thanks for creating a new one.

**Comment by HalosGhost** [comment]
So, on a next update in Arch, everything works again; but neither fontconfig or pango were updated.

I am not sure what happened, or what caused this, but it's no longer an issue. If you want to close this as cannot-reproduce, I wouldn't be annoyed by it.

**Comment by DaveDavenport** [comment]
Ok. lets re-open when more information is available.
